# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-28 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basefiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_filename', models.CharField(max_length=100)),
                ('server_filename', models.CharField(max_length=100)),
                ('last_modified_date', models.IntegerField()),
                ('status', models.IntegerField()),
                ('uploaded_size', models.CharField(max_length=10)),
            ],
        ),
    ]
